version: "3"

services:
  laravel:
    build: ./laravel
    working_dir: /work
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./laravel:/var/www
      - ./laravel/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:1.19.4-alpine
    ports:
      - 8080:80
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./laravel:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    platform: linux/x86_64
    ports:
      - 6306:3306
    depends_on:
      - laravel
    links:
      - laravel

  node:
    image: node:12.13-alpine
    tty: true
    volumes:
      - ./laravel:/var/www
    working_dir: /var/www
    depends_on:
      - laravel
    links:
      - laravel
